import Testing
import UIKit
@testable import Elos

struct ExerciseHowToImageTests {
    @Test func bundledDemoImageResolves() {
        // The de-risk: a synchronized-group .xcassets must compile into the app bundle
        // and be resolvable by the same UIImage(named:) call the how-to sheet uses.
        #expect(UIImage(named: "Butterfly") != nil)
    }

    @Test func additionalBundledImagesResolve() {
        // Spot-check a few more imagesets generated by howto:generate, confirming bulk
        // download produced compilable/resolvable assets for real exercises.
        #expect(UIImage(named: "Barbell_Squat") != nil)
        #expect(UIImage(named: "Barbell_Deadlift") != nil)
        #expect(UIImage(named: "Barbell_Bench_Press_-_Medium_Grip") != nil)
    }
}
