-- Bulk-seed a comprehensive exercise catalog comparable to popular tracking apps.
-- Adds ~170 exercises on top of the 30 seeded by migration 006_create_exercise_definitions.sql.
-- Taxonomy matches migration 006: primary_muscle, secondary_muscles[], equipment, movement_pattern.

INSERT INTO exercise_definitions (name, primary_muscle, secondary_muscles, equipment, movement_pattern) VALUES
  -- ── CHEST (push) ─────────────────────────────────────────────────────────
  ('Dumbbell Bench Press',           'chest',        '{triceps,front_delts}',         'dumbbell',   'push'),
  ('Incline Barbell Bench Press',    'upper_chest',  '{front_delts,triceps}',         'barbell',    'push'),
  ('Decline Barbell Bench Press',    'lower_chest',  '{triceps,front_delts}',         'barbell',    'push'),
  ('Decline Dumbbell Press',         'lower_chest',  '{triceps,front_delts}',         'dumbbell',   'push'),
  ('Dumbbell Fly',                   'chest',        '{front_delts}',                 'dumbbell',   'isolation'),
  ('Incline Dumbbell Fly',           'upper_chest',  '{front_delts}',                 'dumbbell',   'isolation'),
  ('Low Cable Fly',                  'upper_chest',  '{front_delts}',                 'cable',      'isolation'),
  ('High Cable Fly',                 'lower_chest',  '{front_delts}',                 'cable',      'isolation'),
  ('Pec Deck Machine',               'chest',        '{front_delts}',                 'machine',    'isolation'),
  ('Seated Chest Press Machine',     'chest',        '{triceps,front_delts}',         'machine',    'push'),
  ('Incline Chest Press Machine',    'upper_chest',  '{triceps,front_delts}',         'machine',    'push'),
  ('Smith Machine Bench Press',      'chest',        '{triceps,front_delts}',         'machine',    'push'),
  ('Smith Incline Bench Press',      'upper_chest',  '{triceps,front_delts}',         'machine',    'push'),
  ('Wide Push-Up',                   'chest',        '{triceps,front_delts}',         'bodyweight', 'push'),
  ('Diamond Push-Up',                'triceps',      '{chest,front_delts}',           'bodyweight', 'push'),
  ('Decline Push-Up',                'upper_chest',  '{triceps,front_delts}',         'bodyweight', 'push'),
  ('Incline Push-Up',                'lower_chest',  '{triceps,front_delts}',         'bodyweight', 'push'),
  ('Plyometric Push-Up',             'chest',        '{triceps,front_delts}',         'bodyweight', 'push'),
  ('Chest Dip',                      'lower_chest',  '{triceps,front_delts}',         'bodyweight', 'push'),
  ('Dumbbell Pullover',              'chest',        '{lats,triceps}',                'dumbbell',   'isolation'),
  ('Svend Press',                    'chest',        '{front_delts}',                 'dumbbell',   'isolation'),

  -- ── BACK (pull) ──────────────────────────────────────────────────────────
  ('Chin-Up',                        'biceps',       '{lats,rear_delts}',             'bodyweight', 'pull'),
  ('Wide-Grip Pull-Up',              'lats',         '{biceps,rear_delts}',           'bodyweight', 'pull'),
  ('Neutral-Grip Pull-Up',           'lats',         '{biceps,brachialis}',           'bodyweight', 'pull'),
  ('Assisted Pull-Up',               'lats',         '{biceps,rear_delts}',           'machine',    'pull'),
  ('T-Bar Row',                      'lats',         '{biceps,rear_delts,traps}',     'barbell',    'pull'),
  ('Pendlay Row',                    'lats',         '{biceps,rear_delts,traps}',     'barbell',    'pull'),
  ('Meadows Row',                    'lats',         '{biceps,rear_delts}',           'barbell',    'pull'),
  ('Chest-Supported Row',            'lats',         '{biceps,rear_delts}',           'machine',    'pull'),
  ('Inverted Row',                   'lats',         '{biceps,rear_delts}',           'bodyweight', 'pull'),
  ('Yates Row',                      'lats',         '{biceps,rear_delts,traps}',     'barbell',    'pull'),
  ('Seal Row',                       'lats',         '{biceps,rear_delts}',           'barbell',    'pull'),
  ('One-Arm Dumbbell Row',           'lats',         '{biceps,rear_delts}',           'dumbbell',   'pull'),
  ('Reverse-Grip Lat Pulldown',      'lats',         '{biceps}',                      'machine',    'pull'),
  ('Close-Grip Lat Pulldown',        'lats',         '{biceps,rear_delts}',           'machine',    'pull'),
  ('V-Bar Pulldown',                 'lats',         '{biceps}',                      'machine',    'pull'),
  ('Straight-Arm Pulldown',          'lats',         '{}',                            'cable',      'isolation'),
  ('Single-Arm Cable Row',           'lats',         '{biceps,rear_delts}',           'cable',      'pull'),
  ('Kroc Row',                       'lats',         '{biceps,rear_delts,traps}',     'dumbbell',   'pull'),
  ('Hyperextension',                 'lower_back',   '{glutes,hamstrings}',           'bodyweight', 'hinge'),
  ('Reverse Hyperextension',         'glutes',       '{lower_back,hamstrings}',       'machine',    'hinge'),
  ('Good Morning',                   'hamstrings',   '{glutes,lower_back}',           'barbell',    'hinge'),
  ('Rack Pull',                      'back',         '{glutes,hamstrings,traps}',     'barbell',    'hinge'),
  ('Snatch-Grip Deadlift',           'back',         '{glutes,hamstrings,traps}',     'barbell',    'hinge'),
  ('Trap Bar Deadlift',              'quads',        '{glutes,hamstrings,traps}',     'barbell',    'hinge'),
  ('Deficit Deadlift',               'hamstrings',   '{glutes,back}',                 'barbell',    'hinge'),

  -- ── SHOULDERS ────────────────────────────────────────────────────────────
  ('Dumbbell Shoulder Press',        'front_delts',  '{triceps,upper_chest}',         'dumbbell',   'push'),
  ('Arnold Press',                   'front_delts',  '{side_delts,triceps}',          'dumbbell',   'push'),
  ('Seated Dumbbell Press',          'front_delts',  '{triceps}',                     'dumbbell',   'push'),
  ('Seated Barbell Press',           'front_delts',  '{triceps}',                     'barbell',    'push'),
  ('Push Press',                     'front_delts',  '{triceps,quads}',               'barbell',    'push'),
  ('Behind-the-Neck Press',          'side_delts',   '{front_delts,triceps}',         'barbell',    'push'),
  ('Z-Press',                        'front_delts',  '{triceps,core}',                'barbell',    'push'),
  ('Machine Shoulder Press',         'front_delts',  '{triceps}',                     'machine',    'push'),
  ('Smith Shoulder Press',           'front_delts',  '{triceps}',                     'machine',    'push'),
  ('Cable Lateral Raise',            'side_delts',   '{}',                            'cable',      'isolation'),
  ('Machine Lateral Raise',          'side_delts',   '{}',                            'machine',    'isolation'),
  ('Dumbbell Front Raise',           'front_delts',  '{upper_chest}',                 'dumbbell',   'isolation'),
  ('Cable Front Raise',              'front_delts',  '{}',                            'cable',      'isolation'),
  ('Plate Front Raise',              'front_delts',  '{}',                            'dumbbell',   'isolation'),
  ('Bent-Over Lateral Raise',        'rear_delts',   '{traps}',                       'dumbbell',   'isolation'),
  ('Cable Reverse Fly',              'rear_delts',   '{traps}',                       'cable',      'isolation'),
  ('Reverse Pec Deck',               'rear_delts',   '{traps}',                       'machine',    'isolation'),
  ('Upright Row',                    'side_delts',   '{traps,biceps}',                'barbell',    'pull'),
  ('Cable Upright Row',              'side_delts',   '{traps,biceps}',                'cable',      'pull'),
  ('Dumbbell Shrug',                 'traps',        '{}',                            'dumbbell',   'isolation'),
  ('Barbell Shrug',                  'traps',        '{}',                            'barbell',    'isolation'),
  ('Cable Shrug',                    'traps',        '{}',                            'cable',      'isolation'),
  ('Trap Bar Shrug',                 'traps',        '{}',                            'barbell',    'isolation'),
  ('Handstand Push-Up',              'front_delts',  '{triceps}',                     'bodyweight', 'push'),
  ('Pike Push-Up',                   'front_delts',  '{triceps,upper_chest}',         'bodyweight', 'push'),

  -- ── ARMS (biceps) ────────────────────────────────────────────────────────
  ('Barbell Curl',                   'biceps',       '{brachialis,forearms}',         'barbell',    'isolation'),
  ('EZ-Bar Curl',                    'biceps',       '{brachialis,forearms}',         'barbell',    'isolation'),
  ('Preacher Curl',                  'biceps',       '{brachialis}',                  'barbell',    'isolation'),
  ('Cable Curl',                     'biceps',       '{brachialis}',                  'cable',      'isolation'),
  ('Rope Hammer Curl',               'brachialis',   '{biceps,forearms}',             'cable',      'isolation'),
  ('Concentration Curl',             'biceps',       '{}',                            'dumbbell',   'isolation'),
  ('Incline Dumbbell Curl',          'biceps',       '{}',                            'dumbbell',   'isolation'),
  ('Spider Curl',                    'biceps',       '{}',                            'dumbbell',   'isolation'),
  ('Zottman Curl',                   'biceps',       '{forearms,brachialis}',         'dumbbell',   'isolation'),
  ('Reverse Curl',                   'forearms',     '{biceps,brachialis}',           'barbell',    'isolation'),
  ('Cross-Body Hammer Curl',         'brachialis',   '{biceps}',                      'dumbbell',   'isolation'),
  ('Cable Hammer Curl',              'brachialis',   '{biceps}',                      'cable',      'isolation'),
  ('Machine Preacher Curl',          'biceps',       '{brachialis}',                  'machine',    'isolation'),
  ('21s Curl',                       'biceps',       '{}',                            'barbell',    'isolation'),
  ('Drag Curl',                      'biceps',       '{}',                            'barbell',    'isolation'),

  -- ── ARMS (triceps) ───────────────────────────────────────────────────────
  ('Overhead Tricep Extension',      'triceps',      '{}',                            'dumbbell',   'isolation'),
  ('Rope Tricep Extension',          'triceps',      '{}',                            'cable',      'isolation'),
  ('Single-Arm Tricep Pushdown',     'triceps',      '{}',                            'cable',      'isolation'),
  ('Overhead Cable Tricep Extension','triceps',      '{}',                            'cable',      'isolation'),
  ('Bench Dip',                      'triceps',      '{front_delts}',                 'bodyweight', 'push'),
  ('Parallel Bar Dip',               'triceps',      '{lower_chest,front_delts}',     'bodyweight', 'push'),
  ('Tricep Kickback',                'triceps',      '{}',                            'dumbbell',   'isolation'),
  ('Cable Tricep Kickback',          'triceps',      '{}',                            'cable',      'isolation'),
  ('JM Press',                       'triceps',      '{chest}',                       'barbell',    'isolation'),
  ('California Press',               'triceps',      '{chest}',                       'dumbbell',   'isolation'),
  ('Tate Press',                     'triceps',      '{}',                            'dumbbell',   'isolation'),
  ('Machine Tricep Extension',       'triceps',      '{}',                            'machine',    'isolation'),

  -- ── FOREARMS ─────────────────────────────────────────────────────────────
  ('Wrist Curl',                     'forearms',     '{}',                            'barbell',    'isolation'),
  ('Reverse Wrist Curl',             'forearms',     '{}',                            'barbell',    'isolation'),
  ('Behind-the-Back Wrist Curl',     'forearms',     '{}',                            'barbell',    'isolation'),
  ('Farmer''s Walk',                 'forearms',     '{traps,core}',                  'dumbbell',   'carry'),
  ('Plate Pinch',                    'forearms',     '{}',                            'dumbbell',   'carry'),

  -- ── LEGS (quads) ─────────────────────────────────────────────────────────
  ('Goblet Squat',                   'quads',        '{glutes,core}',                 'dumbbell',   'squat'),
  ('Bulgarian Split Squat',          'quads',        '{glutes,hamstrings}',           'dumbbell',   'squat'),
  ('Walking Lunge',                  'quads',        '{glutes,hamstrings}',           'dumbbell',   'squat'),
  ('Reverse Lunge',                  'glutes',       '{quads,hamstrings}',            'dumbbell',   'squat'),
  ('Step-Up',                        'quads',        '{glutes}',                      'dumbbell',   'squat'),
  ('Hack Squat Machine',             'quads',        '{glutes}',                      'machine',    'squat'),
  ('Smith Machine Squat',            'quads',        '{glutes,hamstrings}',           'machine',    'squat'),
  ('Box Squat',                      'quads',        '{glutes,hamstrings}',           'barbell',    'squat'),
  ('Pause Squat',                    'quads',        '{glutes,hamstrings}',           'barbell',    'squat'),
  ('Pistol Squat',                   'quads',        '{glutes,core}',                 'bodyweight', 'squat'),
  ('Sissy Squat',                    'quads',        '{}',                            'bodyweight', 'isolation'),
  ('Belt Squat',                     'quads',        '{glutes}',                      'machine',    'squat'),
  ('Cyclist Squat',                  'quads',        '{glutes}',                      'barbell',    'squat'),
  ('Cossack Squat',                  'quads',        '{glutes,adductors}',            'bodyweight', 'squat'),
  ('Lateral Lunge',                  'adductors',    '{quads,glutes}',                'dumbbell',   'squat'),
  ('Wall Sit',                       'quads',        '{glutes}',                      'bodyweight', 'isolation'),
  ('Jump Squat',                     'quads',        '{glutes,calves}',               'bodyweight', 'squat'),

  -- ── LEGS (hamstrings) ────────────────────────────────────────────────────
  ('Stiff-Leg Deadlift',             'hamstrings',   '{glutes,lower_back}',           'barbell',    'hinge'),
  ('Single-Leg Romanian Deadlift',   'hamstrings',   '{glutes,core}',                 'dumbbell',   'hinge'),
  ('Dumbbell Romanian Deadlift',     'hamstrings',   '{glutes}',                      'dumbbell',   'hinge'),
  ('Lying Leg Curl',                 'hamstrings',   '{}',                            'machine',    'isolation'),
  ('Seated Leg Curl',                'hamstrings',   '{}',                            'machine',    'isolation'),
  ('Nordic Hamstring Curl',          'hamstrings',   '{}',                            'bodyweight', 'isolation'),
  ('Glute-Ham Raise',                'hamstrings',   '{glutes}',                      'bodyweight', 'isolation'),
  ('Kettlebell Swing',               'glutes',       '{hamstrings,core}',             'dumbbell',   'hinge'),

  -- ── LEGS (calves) ────────────────────────────────────────────────────────
  ('Standing Calf Raise',            'calves',       '{}',                            'machine',    'isolation'),
  ('Seated Calf Raise',              'calves',       '{}',                            'machine',    'isolation'),
  ('Donkey Calf Raise',              'calves',       '{}',                            'machine',    'isolation'),
  ('Single-Leg Calf Raise',          'calves',       '{}',                            'bodyweight', 'isolation'),
  ('Tibialis Raise',                 'calves',       '{}',                            'bodyweight', 'isolation'),
  ('Smith Machine Calf Raise',       'calves',       '{}',                            'machine',    'isolation'),

  -- ── GLUTES ───────────────────────────────────────────────────────────────
  ('Barbell Hip Thrust',             'glutes',       '{hamstrings,core}',             'barbell',    'hinge'),
  ('Single-Leg Hip Thrust',          'glutes',       '{hamstrings,core}',             'bodyweight', 'hinge'),
  ('Machine Hip Thrust',             'glutes',       '{hamstrings}',                  'machine',    'hinge'),
  ('Cable Pull-Through',             'glutes',       '{hamstrings,lower_back}',       'cable',      'hinge'),
  ('Glute Bridge',                   'glutes',       '{hamstrings}',                  'bodyweight', 'hinge'),
  ('Single-Leg Glute Bridge',        'glutes',       '{hamstrings,core}',             'bodyweight', 'hinge'),
  ('Cable Kickback',                 'glutes',       '{}',                            'cable',      'isolation'),
  ('Donkey Kick',                    'glutes',       '{}',                            'bodyweight', 'isolation'),
  ('Frog Pump',                      'glutes',       '{}',                            'bodyweight', 'isolation'),
  ('Hip Abductor Machine',           'glutes',       '{}',                            'machine',    'isolation'),
  ('Hip Adductor Machine',           'adductors',    '{}',                            'machine',    'isolation'),
  ('Curtsy Lunge',                   'glutes',       '{quads,adductors}',             'dumbbell',   'squat'),
  ('B-Stance Hip Thrust',            'glutes',       '{hamstrings}',                  'barbell',    'hinge'),

  -- ── CORE ─────────────────────────────────────────────────────────────────
  ('Side Plank',                     'obliques',     '{core,glutes}',                 'bodyweight', 'carry'),
  ('Hanging Leg Raise',              'core',         '{hip_flexors}',                 'bodyweight', 'isolation'),
  ('Hanging Knee Raise',             'core',         '{hip_flexors}',                 'bodyweight', 'isolation'),
  ('Toes-to-Bar',                    'core',         '{hip_flexors,lats}',            'bodyweight', 'isolation'),
  ('Captain''s Chair Leg Raise',     'core',         '{hip_flexors}',                 'machine',    'isolation'),
  ('Cable Crunch',                   'core',         '{}',                            'cable',      'isolation'),
  ('Crunch',                         'core',         '{}',                            'bodyweight', 'isolation'),
  ('Sit-Up',                         'core',         '{hip_flexors}',                 'bodyweight', 'isolation'),
  ('Decline Sit-Up',                 'core',         '{hip_flexors}',                 'bodyweight', 'isolation'),
  ('Weighted Crunch',                'core',         '{}',                            'dumbbell',   'isolation'),
  ('Russian Twist',                  'obliques',     '{core}',                        'dumbbell',   'rotation'),
  ('Bicycle Crunch',                 'core',         '{obliques,hip_flexors}',        'bodyweight', 'isolation'),
  ('V-Up',                           'core',         '{hip_flexors}',                 'bodyweight', 'isolation'),
  ('Dead Bug',                       'core',         '{}',                            'bodyweight', 'isolation'),
  ('Bird Dog',                       'core',         '{glutes,lower_back}',           'bodyweight', 'isolation'),
  ('Pallof Press',                   'obliques',     '{core}',                        'cable',      'rotation'),
  ('Cable Woodchopper',              'obliques',     '{core}',                        'cable',      'rotation'),
  ('Ab Wheel Rollout',               'core',         '{lats}',                        'bodyweight', 'isolation'),
  ('L-Sit',                          'core',         '{hip_flexors,triceps}',         'bodyweight', 'isolation'),
  ('Dragon Flag',                    'core',         '{hip_flexors,lats}',            'bodyweight', 'isolation'),
  ('Hollow Body Hold',               'core',         '{hip_flexors}',                 'bodyweight', 'isolation'),
  ('Mountain Climber',               'core',         '{hip_flexors,front_delts}',     'bodyweight', 'isolation'),

  -- ── OLYMPIC / EXPLOSIVE ──────────────────────────────────────────────────
  ('Power Clean',                    'traps',        '{quads,glutes,hamstrings}',     'barbell',    'pull'),
  ('Power Snatch',                   'traps',        '{quads,glutes,front_delts}',    'barbell',    'pull'),
  ('Clean and Jerk',                 'front_delts',  '{quads,glutes,traps}',          'barbell',    'push'),
  ('Hang Clean',                     'traps',        '{quads,glutes,hamstrings}',     'barbell',    'pull'),
  ('Box Jump',                       'quads',        '{glutes,calves}',               'bodyweight', 'squat'),
  ('Broad Jump',                     'quads',        '{glutes,hamstrings}',           'bodyweight', 'squat'),
  ('Medicine Ball Slam',             'core',         '{front_delts,lats}',            'dumbbell',   'rotation');

-- Add a partial unique index on global (non-custom) exercises to prevent future duplicate seeds.
CREATE UNIQUE INDEX IF NOT EXISTS exercise_definitions_global_name_uniq
  ON exercise_definitions (lower(name))
  WHERE owner_id IS NULL;
