import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { pool } from "../../db";
import { matchCatalog, type SourceExercise, type CatalogExercise } from "./matcher";
import { NAME_ALIASES, MUSCLE_MAP, MACHINE_GAP_FILLS } from "./aliases";

const REPO_ROOT = join(__dirname, "..", "..", "..", "..", "..");
const SOURCE = join(REPO_ROOT, "data", "free-exercise-db.exercises.json");
const MIGRATION_OUT = join(__dirname, "..", "..", "..", "migrations", "037_seed_exercise_howto.sql");
const REPORT_OUT = join(REPO_ROOT, "docs", "superpowers", "artifacts", "2026-07-03-howto-match-report.csv");

const sq = (s: string) => `'${s.replace(/'/g, "''")}'`;
const pgTextArray = (arr: string[]) => `ARRAY[${arr.map((s) => sq(s)).join(", ")}]::text[]`;

async function main() {
  // Sanity-check REPO_ROOT resolution
  console.log(`REPO_ROOT: ${REPO_ROOT}`);
  console.log(`SOURCE:    ${SOURCE}`);

  const source: SourceExercise[] = JSON.parse(readFileSync(SOURCE, "utf8"));
  const { rows } = await pool.query<CatalogExercise>(
    "SELECT name, movement_pattern FROM exercise_definitions WHERE owner_id IS NULL"
  );
  const { enriched, unmatched } = matchCatalog(rows, source, NAME_ALIASES, MUSCLE_MAP);

  const lines: string[] = [
    "-- GENERATED by src/scripts/howto/generate.ts. Do not hand-edit; re-run howto:generate.",
    "-- Enriches matched exercises with how-to content and backfills movement_pattern;",
    "-- inserts curated machine gap-fill exercises. Re-runnable (guarded).",
    "",
  ];
  for (const e of enriched) {
    lines.push(
      `UPDATE exercise_definitions SET instructions = ${pgTextArray(e.instructions)}, image_key = ${sq(e.imageKey)} ` +
      `WHERE lower(name) = lower(${sq(e.elosName)}) AND owner_id IS NULL;`
    );
    lines.push(
      `UPDATE exercise_definitions SET movement_pattern = ${sq(e.derivedMovementPattern)} ` +
      `WHERE lower(name) = lower(${sq(e.elosName)}) AND owner_id IS NULL AND movement_pattern = '';`
    );
  }
  lines.push("");
  const srcByName = new Map(source.map((s) => [s.name, s]));
  for (const g of MACHINE_GAP_FILLS) {
    const src = srcByName.get(g.sourceName);
    if (!src) { console.warn(`gap-fill source not found: ${g.sourceName}`); continue; }
    lines.push(
      `INSERT INTO exercise_definitions (name, primary_muscle, secondary_muscles, equipment, movement_pattern, instructions, image_key) ` +
      `SELECT ${sq(g.elosName)}, ${sq(g.primaryMuscle)}, ${pgTextArray(g.secondaryMuscles)}, ${sq(g.equipment)}, ${sq(g.movementPattern)}, ${pgTextArray(src.instructions)}, ${sq(src.id)} ` +
      `WHERE NOT EXISTS (SELECT 1 FROM exercise_definitions WHERE lower(name) = lower(${sq(g.elosName)}) AND owner_id IS NULL);`
    );
  }
  writeFileSync(MIGRATION_OUT, lines.join("\n") + "\n");

  mkdirSync(dirname(REPORT_OUT), { recursive: true });
  const csv = ["elos_name,source_name,image_key,status"];
  for (const e of enriched) csv.push(`${sq(e.elosName)},${sq(e.sourceName)},${e.imageKey},matched`);
  for (const u of unmatched) csv.push(`${sq(u)},,,unmatched`);
  writeFileSync(REPORT_OUT, csv.join("\n") + "\n");

  console.log(`Enriched: ${enriched.length}  Unmatched: ${unmatched.length}  Gap-fills: ${MACHINE_GAP_FILLS.length}`);
  console.log(`Wrote ${MIGRATION_OUT}`);
  console.log(`Wrote ${REPORT_OUT}`);
  await pool.end();
}
main().catch((err) => { console.error(err); process.exit(1); });
